"""Offline replay must reproduce the live runs it was snapshotted from.

Fixtures are generated by `python -m skuforge.snapshot` from records the
pipeline really produced, so a drift here means either the pipeline changed
behaviour or the fixtures were regenerated from a contaminated record.
"""
import os

os.environ["SKUFORGE_MOCK"] = "1"

import pytest  # noqa: E402

from skuforge.models import SKUInput  # noqa: E402
from skuforge.orchestrator import run_sku  # noqa: E402

# (sku, expected attributes, expected conflicts, expected category)
RECORDED = [
    (
        SKUInput(mpn="HOM230CP", brand="Square D", description="30A 2 pole breaker"),
        13, 2, "circuit_breaker",
    ),
    (
        SKUInput(
            mpn="1451-2W", brand="Leviton", description="15A single pole switch white"
        ),
        10, 1, "switch",
    ),
]


@pytest.mark.parametrize("sku,n_attrs,n_conflicts,category", RECORDED)
def test_replay_matches_recorded_run(sku, n_attrs, n_conflicts, category):
    record = run_sku(sku)
    assert record.category == category
    assert len(record.attributes) == n_attrs
    conflicts = [a for a in record.attributes if a.conflicting_values]
    assert len(conflicts) == n_conflicts
    assert record.provider == "mock", "replayed records must be marked as mock"
    assert record.seo_title, "composer output should replay too"


def test_replay_preserves_provenance():
    """Every attribute keeps a quote and a real source URL, not a redirector."""
    record = run_sku(RECORDED[1][0])
    for attr in record.attributes:
        assert attr.evidence, f"{attr.name} lost its evidence"
        for ev in attr.evidence:
            assert ev.source_url.startswith("http")
            assert "grounding-api-redirect" not in ev.source_url
